name: Run WebDriverIO Tests

on:
  workflow_call:
    inputs:
      scenario-tags:
        required: true
        type: string
      spec:
        required: false
        type: string
      is-alt-run:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set dynamic run name
        run: echo "TESTRAIL_RUN_NAME=Automated schedule execution on $(date +"%Y-%m-%d")" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install
        
      - name: Trigger ${{ inputs.scenario-tags }} Script
        uses: nick-fields/retry@v2
        if: success() || failure()
        with:
          timeout_minutes: 100
          max_attempts: 2
          retry_on: error
          command: |
            export HEADLESS=true
            npx wdio run ./wdio.conf.js --spec=${{ inputs.spec }} --mochaOpts.grep ${{ inputs.scenario-tags }}
      - name: Run WebDriverIO Tests
        env:
          TESTRAIL_RUN_NAME: ${{ env.TESTRAIL_RUN_NAME }}
        run: npm run wdio

